function showQuote() {
  const quotes = [
    "You're allowed to outgrow people.",
    "Not all storms come to destroy you.",
    "Healing isn’t linear – go at your pace.",
    "This pain has a purpose.",
    "Your worth isn't tied to someone else's inability to love you.",
    "Let them go, you’re not their home anymore.",
    "Even flowers bloom after being buried.",
    "Your future self is proud of you.",
    "Some endings are sacred beginnings.",
    "You don’t need closure to move on.",
    "You were never too much – just too real.",
    "Soft hearts survive the harshest winters.",
    "Someone out there is praying for a soul like yours.",
    "You were the sun; they just weren’t ready for daylight.",
    "Your energy is sacred, not everyone deserves access.",
    "Every tear is watering your growth.",
    "The love you gave will return tenfold.",
    "You are not alone in your healing.",
    "One day you'll smile for no reason again.",
    "Don't beg for love – become it.",
    "Being alone is better than being misunderstood.",
    "You’re not a chapter – you’re the whole book.",
    "Some people are just lessons, not lifetimes.",
    "You were a blessing they couldn't hold.",
    "Choose yourself every single time.",
    "You weren’t rejected, you were redirected.",
    "The one who’s meant for you will understand your silence.",
    "You're not broken – you're rebuilding.",
    "You are not hard to love.",
    "Healing starts when you stop blaming yourself.",
    "You're still art, even with cracks.",
    "Your peace matters more than their presence.",
    "Your love is a gift, not a loan.",
    "Some hearts need to break to finally open.",
    "Walk away like the blessing you are.",
    "You were the lesson they needed to grow.",
    "Your glow-up starts with letting go.",
    "Your soul didn't come this far to settle.",
    "Even stars burn out to shine brighter.",
    "Every goodbye is making space for a better hello.",
    "Your love wasn’t wasted, it was sacred.",
    "Let go, not to lose them, but to find you.",
    "You don’t chase love, you attract it.",
    "Stop shrinking to fit places you’ve outgrown.",
    "Don’t reopen doors that hurt you to close.",
    "Real love doesn’t leave without trying.",
    "They lost someone who would’ve stayed.",
    "Your softness is still your strength.",
    "You were not too sensitive – you were in tune.",
    "You are the home you were searching for.",
    "Feel it, heal it, release it.",
    "Start romanticizing your alone time.",
    "Growth is painful. So is staying the same.",
    "You’re not a backup plan.",
    "Leave space for what’s meant to find you.",
    "One day this will all make sense.",
    "Let go with grace, not guilt.",
    "Your scars are proof you survived.",
    "The right love won't confuse you.",
    "Healing is choosing yourself again and again.",
    "You’re not late – you’re aligning.",
    "Don't water dead plants.",
    "You were not asking for too much.",
    "Real love is rooted, not rushed.",
    "You’re not hard to love – they were unready.",
    "Your glow is coming – stay soft.",
    "What broke you once will never define you.",
    "You’re allowed to miss them and still move on.",
    "You are your own rescue story.",
    "Self-love is your new superpower.",
    "Fall in love with your healing era.",
    "What’s gone was not meant to stay.",
    "Pain doesn’t mean you failed – it means you felt.",
    "Losing them might be saving you.",
    "Protect your peace like it’s gold.",
    "Let your healing shock the world.",
    "Healing is a radical act of self-love.",
    "You were not difficult – you were deep.",
    "Don’t dim for anyone again.",
    "Their inability to love isn’t your fault.",
    "You didn’t lose them – you found you.",
    "Trust the space between heartbreak and healing.",
    "You are worth choosing every day.",
    "Cry. Cleanse. Carry on.",
    "You will love again – deeper, wiser.",
    "Release what weighs you.",
    "You were never the problem.",
    "Better love is on its way.",
    "Thank your past, then walk away.",
    "You don’t need to be fixed – just felt.",
    "It's okay to restart as many times as needed.",
    "Love didn’t fail you – people did.",
    "This chapter ends so a better one can begin.",
    "They were a stop, not a destination.",
    "Don’t go back to what broke you.",
    "You are a whole world on your own.",
    "Let it hurt, but don’t let it harden you.",
    "You owe no one an explanation for your peace.",
    "What’s meant will never feel forced.",
    "You’re still magic even if they missed it.",
    "Turn heartbreak into healing fuel.",
    "They couldn’t meet you where you were headed.",
    "You’re not behind, you’re blooming.",
    "Start over, beautifully.",
    "Give yourself the closure they never could.",
    "Love yourself so hard it feels like revenge.",
    "Some people leave so peace can enter.",
    "Be the love you seek.",
    "You are the muse now.",
    "This pain is proof you're alive and growing.",
    "You didn’t lose love – you learned it.",
    "Walk away glowing, not grieving.",
    "The right love will hold space, not control.",
    "A soft life starts with hard choices.",
    "Don’t let a moment of sadness define your forever.",
    "You are rare – protect that.",
    "The one who’s meant will see you, fully.",
    "Your love deserves to be returned.",
    "Reclaim your time, your peace, your power.",
    "You’re not healing for them, you’re healing for you.",
    "Never apologize for outgrowing chaos.",
    "You are the light they couldn’t hold."
  ];
  
  
  const quote = quotes[Math.floor(Math.random() * quotes.length)];
  document.getElementById("quote").textContent = quote;
}

  function releaseVent() {
    const ventText = document.getElementById("ventText").value.trim();

    if (ventText === "") {
      alert("Please type something first 📝");
      return;
    }
    const messages = [
      "Your pain has found a voice. Healing begins now ✨",
      "You’ve set your emotions free — breathe easy 💨",
      "That weight is off your chest. You’re stronger already 💪",
      "Your feelings are valid — and now they’ve been heard 💖",
      "Dark thoughts out, light coming in 🌅",
      "You’ve taken the first step. Healing starts here 🌿",
      "You let it out — now let peace in ☁️",
      "That took courage. Proud of you 🫶",
      "You just unlocked another level of healing 🔓",
      "Your heart whispered, and you listened 🫀💬"
    ];
    
    const randomMsg = messages[Math.floor(Math.random() * messages.length)];
    alert(randomMsg);
  }


